/**
 * The line under the wordmark, rotated on a timer.
 *
 * House jokes and forum-shaped one-liners, deliberately shuffled so the
 * regulars are scattered through the rotation instead of arriving in a block.
 * The order here is the order the page walks, and each visit starts at a
 * different point (see `src/client/client.ts`).
 *
 * Keep every line under 78 characters: the layout reserves two lines of the
 * 40ch measure and never resizes, so a longer line would be clipped.
 * `test/taglines.test.ts` enforces that.
 */
export const TAGLINES: readonly string[] = [
  "Where undocumented behaviour gets documented.",
  "Is it kosher? Start a thread.",
  "Sorted by oldest, because that is where the truth is.",
  "flippy is too normal for this place.",
  "Thread necromancy is a load-bearing feature.",
  "Strong opinions, loosely versioned.",
  "Solved it myself, posting for the archive.",
  "anon fliphones his views twice a thread.",
  "No SLA. No budget. No downtime either.",
  "Somebody's homework, somebody's production outage.",
  "Silent all Shabbos. Loud by havdalah.",
  "We reverse-engineered the polite way: together.",
  "The spam filter has seen things.",
  "Ars18 will hack it. Give him the afternoon.",
  "Hosted on hope and a spare box.",
  "Kosher by whose hechsher?",
  "Necroposting is just long-form memory.",
  "Read-only until you have read a lot.",
  "Faster than the docs. Rougher than the docs.",
  "shalom karr will do it. Well, his AI will.",
  "Reproduced. Confirmed. Ignored upstream.",
  "Typed on T9. Every letter earned.",
  "Someone here has already broken it your way.",
  "chatzie is oversmart and shows his work.",
  "Sort by controversial for the good engineering.",
  "Threads that end in a wiki are the best threads.",
  "Two users, three filters, four opinions.",
  "Ask here before you ask support.",
  "Less screen time. After this thread.",
  "Post count is not a personality. Allegedly.",
  "Institutional memory with a login page.",
  "Blocked by the filter we recommend.",
  "Every edge case has a username attached.",
  "A wiki that argues back.",
  "Read the whole thread. It gets better.",
  "The screenshot is 400x300 and that is final.",
  "Studied the release notes b'chavrusa.",
  "Works on my machine, documented for yours.",
  "Bug reports that outlived the company.",
  "Still the top result. Still correct.",
  "Motzei Shabbos, the inbox catches up.",
  "Someone kept the changelog. It was not the vendor.",
  "Captcha solved. Trust unearned.",
  "The real docs, written at 2am by volunteers.",
  "Bitul zman? This is research.",
  "leo buskin is back! Nobody knows from where.",
  "The three most feared words: never mind, solved.",
  "Solved, marked solved, still argued about.",
  "The changelog has its gedolim.",
  "Someone in 2031 needs this thread.",
  "kosherflipper, a mourned loss.",
  "The workaround is now the standard.",
  "Do not post the workaround. Yes, that one.",
  "Welcome. Lurk first.",
  "Someone bisected it on a weekend.",
  "Your first post is held for review. Sorry.",
  "Every heter has a thread.",
  "flipadmin makes peace. It lasts a page.",
  "We argued for six pages and shipped it.",
  "Ask your rov. Then read the thread anyway.",
  "One post, four tangents, zero regrets.",
  "Marked resolved by the person who gave up.",
  "Rep points buy nothing and mean everything.",
  "Rollback instructions, lovingly maintained.",
  "No browser, no camera, no problem.",
  "The mods are asleep. Post cursed configs.",
  "Flame war resolved by a pull request.",
  "A machlokes l'shem shamayim, with screenshots.",
  "An archive that answers back.",
  "Second reply: the actual answer.",
  "Half the answers begin with actually.",
  "Kosher phone, treif opinions.",
  "Nobody is paid and it still works.",
  "The whitelist is never long enough.",
  "Attached: config.txt. Renamed: config.txt.txt.",
  "Cached by strangers, forever.",
  "Your neshama outranks your notifications.",
  "Signature longer than the post.",
  "Every workaround has a story and a grudge.",
  "Uptime by stubbornness.",
  "Whitelisted after three emails and a phone call.",
  "Filed upstream. Fixed here first.",
  "Locked for your own good.",
  "Ten years of institutional memory, badly indexed.",
  "Elu v'elu, but check the pinned post.",
  "It is not gatekeeping, it is a reading list.",
  "Support asks here too.",
  "Still maintained by people who do not have to.",
  "EDIT: fixed it. No further detail.",
  "Three-day yom tov, forty new threads.",
  "donbot times are over. Pour one out.",
  "A support ticket that talks back.",
  "Where dead links go to be re-uploaded.",
  "Nine years later, someone finally replies.",
  "If it needs an app store, it is treif here.",
  "Long threads are just slow books.",
  "The best answer has three upvotes and no badge.",
  "Write it down. That is the whole website.",
  "Same question. Different decade.",
  "Everyone here has a rav. Nobody quotes the same one.",
  "We found the regression before the release notes.",
  "dev-in-the-bm is always right. It has been checked.",
  "The archive nobody funds and everybody reads.",
  "Ask badly. Get answered anyway.",
  "Warranty void, thread alive.",
  "kosherboys simplicity: one line, no context, correct.",
  "Mirror in the next post, as always.",
  "The product died. The thread did not.",
  "Your rebbe warned you about sites like this.",
  "biden2020prez is a narcesist and admits it.",
  "The badge system was a mistake we love.",
  "B'ezras Hashem, v2 ships motzei Shabbos.",
  "The last known copy of that firmware lives here.",
  "Someone else will find it for you anyway.",
  "Bump.",
  "New user, old problem.",
  "The FAQ was written from these arguments.",
  "Somewhere a bochur is reading this on a Qin.",
  "TripleU loves arguing more than winning.",
  "The most useful post is always an edit.",
  "Even AI needs a break from shalom karr.",
  "Instructions unclear. Thread now 40 pages.",
  "The answer was in the third reply all along.",
  "First reply: why would you want to do that?",
  "Every fix here started as a complaint.",
  "Search first. You won't. We know.",
  "TripleU is a boogy man. Nobody saw him log off.",
  "Where the thread is the documentation.",
  "Version 2.1 broke it. Page 12 fixed it.",
  "Page 1 asks. Page 6 answers. Page 7 fights.",
  "Edited 14 times. Still wrong.",
  "Quoting the entire thread to add: same.",
  "Someone will say: just use the search.",
  "Achievement unlocked: replied to yourself.",
  "RTFM, but we wrote the M.",
  "Consensus reached. Nobody agrees.",
  "Introduce yourself. Nobody will notice.",
  "Peer review, but the peers are angry.",
  "This place is a changelog with feelings.",
  "Please say what you did. Please.",
  "The oral tradition, but searchable.",
  "Vendor said impossible. Page 3 says otherwise.",
  "The upgrade guide nobody was paid to write.",
  "The good stuff is in the replies to the replies.",
  "Buried on page four: the actual fix.",
  "Off-topic by page two. On-topic by page nine.",
  "Undocumented flag, thoroughly documented.",
  "Report button works. Patience varies.",
  "Merged into a thread from 2011.",
  "Mods: unpaid, unthanked, unbothered.",
  "Duplicate of a question nobody answered either.",
  "froggy left. Still sad about it.",
  "The other half begin with: finally, someone asked.",
  "Google sends you here. So does everyone.",
  "Rule one: search. Rule two: nobody searches.",
  "The tutorial is a forum post from 2013.",
];

if (TAGLINES.length === 0) {
  throw new Error("taglines: the list is empty");
}
